//go:build ignore

// Command gen regenerates table.go from the gemoji dataset.
//
//	go run gen.go
//
// gemoji is GitHub's emoji database, and is the same source the shortcodes in
// Rocket.Chat, Slack and GitHub itself are drawn from, so `:joy:` means the same
// thing everywhere.
package main

import (
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"os"
	"sort"
	"strings"
)

const source = "https://raw.githubusercontent.com/github/gemoji/master/db/emoji.json"

type entry struct {
	Emoji       string   `json:"emoji"`
	Description string   `json:"description"`
	Category    string   `json:"category"`
	Aliases     []string `json:"aliases"`
	Tags        []string `json:"tags"`
}

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "gen:", err)
		os.Exit(1)
	}
}

func run() error {
	resp, err := http.Get(source)
	if err != nil {
		return err
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		return fmt.Errorf("fetch %s: %s", source, resp.Status)
	}
	raw, err := io.ReadAll(resp.Body)
	if err != nil {
		return err
	}

	var entries []entry
	if err := json.Unmarshal(raw, &entries); err != nil {
		return err
	}

	// Deterministic output so regenerating produces no spurious diff.
	sort.Slice(entries, func(i, j int) bool {
		return primary(entries[i]) < primary(entries[j])
	})

	var b strings.Builder
	b.WriteString(`// Code generated by gen.go; DO NOT EDIT.
// Source: ` + source + `

package emoji

// table is every emoji with a shortcode, sorted by canonical shortcode.
var table = []Emoji{
`)
	count := 0
	for _, e := range entries {
		if e.Emoji == "" || len(e.Aliases) == 0 {
			continue
		}
		count++
		fmt.Fprintf(&b, "\t{%q, %q, %s, %q, %s},\n",
			primary(e), e.Emoji, quoteList(e.Aliases[1:]), e.Category, quoteList(e.Tags))
	}
	b.WriteString("}\n")

	if err := os.WriteFile("table.go", []byte(b.String()), 0o644); err != nil {
		return err
	}
	fmt.Printf("wrote table.go with %d emoji\n", count)
	return nil
}

func primary(e entry) string {
	if len(e.Aliases) == 0 {
		return ""
	}
	return e.Aliases[0]
}

func quoteList(values []string) string {
	if len(values) == 0 {
		return "nil"
	}
	quoted := make([]string, len(values))
	for i, v := range values {
		quoted[i] = fmt.Sprintf("%q", v)
	}
	return "[]string{" + strings.Join(quoted, ", ") + "}"
}
